### ISSUE TITLE
Fail to connect 

### ISSUE THREAD

**Issue by wr125** [SbstnErhrdt/go-gorm-all-sql#1]
2021/09/03 15:08:04 /home/rest/models/base.go:34 SLOW SQL >= 200ms
[440.751ms] [rows:0] CREATE TABLE `accounts` (`id` bigint unsigned AUTO_INCREMENT,`created_at` datetime(3) NULL,`updated_at` datetime(3) NULL,`deleted_at` datetime(3) NULL,`email` longtext,`password` longtext,`token` longtext,PRIMARY KEY (`id`),INDEX idx_accounts_deleted_at (`deleted_at`))

2021/09/03 15:08:05 /home/rest/models/base.go:34 SLOW SQL >= 200ms
[424.219ms] [rows:0] CREATE TABLE `contacts` (`id` bigint unsigned AUTO_INCREMENT,`created_at` datetime(3) NULL,`updated_at` datetime(3) NULL,`deleted_at` datetime(3) NULL,`name` longtext,`phone` longtext,`user_id` bigint unsigned,PRIMARY KEY (`id`),INDEX idx_contacts_deleted_at (`deleted_at`))
INFO[0001] Environment variable SQL_HOST is missing. Please add the variable to your environment to connect to the database 
INFO[0001] Environment variable SQL_USER is missing. Please add the variable to your environment to connect to the database 
INFO[0001] Environment variable SQL_PASSWORD is missing. Please add the variable to your environment to connect to the database 
INFO[0001] Environment variable SQL_PORT is missing. Please add the variable to your environment to connect to the database 

using the 2.0 version of gorm to connect.
db, err := gorm.Open(mysql.Open(dsn), &gorm.Config{})
	if err != nil {
		panic("can't connect to database")
	}
so when you say just state your using sql_type (mysql in my case) and your good to go, what do you mean? I also have a .env file in directory with the following 
SQL_HOST=127.0.0.1
SQL_USER=user
SQL_PASSWORD=password
SQL_PORT=3306
SQL_DATABASE=dbname
SQL_LOGGER=LOGRUS

**Comment by SbstnErhrdt** [comment]
Hi @wr125 , 
the idea behind this repository is to have a "generic" SQL interface for PostGres, MySQL, MSSQL, ... 

To determine the type of SQL, an environment variable is used. 
So the package checks for this `SQL_TYPE ` variable.

To load the .env file you can use various libraries ... 
I have extended github.com/joho/godotenv with a fallback function for missing environment variables: github.com/SbstnErhrdt/env. 

In that case your code would look like this:
```
func main() {
	// load env
	env.LoadEnvFiles() // reads the .env file in the working directory
	// connect to sql
	db, err := sql.ConnectToDatabase()
	...
```

In a production setting you would then just set the environment and start the application.

I'm expanding the readme a bit so hopefully it will be clearer :-)

**Comment by SbstnErhrdt** [comment]
your `.env` file would look like this:

```
SQL_TYPE=MYSQL
SQL_HOST=127.0.0.1
SQL_USER=user
SQL_PASSWORD=password
SQL_PORT=3306
SQL_DATABASE=dbname
SQL_LOGGER=LOGRUS
```

**Comment by wr125** [comment]
ok thanks for the quick response. Making good progress. However, the following db receives not in use until i use db.AutoMigrate(&Account{}, &Contact{}) as recommended by gorm 2.0. But the 2 tables are not recognised the the compiler. Not in its path. Unfortunately, gorm does not example this on their site how to create tables outside of main.go. which is impractical for models.go.

**Comment by SbstnErhrdt** [comment]
I would recommend to create a package / folder that is called `connections` and a file that is called `sql.go`.

```go
package connections

import (
	"github.com/SbstnErhrdt/go-gorm-all-sql/pkg/sql"
	log "github.com/sirupsen/logrus"
	"gorm.io/gorm"
)

var SQLClient *gorm.DB

// ConnectToSQL inits a sql client
func ConnectToSQL() {
	log.Println("Try to connect to sql database")
	client, err := sql.ConnectToDatabase()
	if err != nil {
		log.Error("Failed to connected to sql database")
		panic(err)
		return
	}
	SQLClient = client
	log.Info("Successfully connected to sql database")
	return
}
``` 

In you main.go you connect to the DB via 
```go
func main() {
   connections.ConnectToSQL()
   ...
}
```
And then you init your app logic.

In your other files e.g. `controllers.go` you can simply go with
```go
func GetUsers() ([]models.User, error) {
   results := []models.User{}
   err := connections.SQLClient.Find(&results).Error
  ...
}
```

I hope that helps

**Comment by wr125** [comment]
ok and thanks for the feedback. However, i am getting "use of package env without selector" error after trying to add env to this line 	db, err := gorm.Open(mysql.Open(env), &gorm.Config{}) env = dns which is a connection "string" that should be handled. directory structure looks like this; app, controllers, models, util and now connections

**Comment by SbstnErhrdt** [comment]
Sorry that does not make any sense.

You are mixing up various things here.

To run your code, you do not need this package here at all.

The following code should server your purpose.
```go
func main() {
	// load env
	env.LoadEnvFiles() 
        dsn := env.FallbackEnvVariable("SQL_CONNECTOR","user:pass@tcp(127.0.0.1:3306)/dbname?charset=utf8mb4&parseTime=True&loc=Local")
       db, err := gorm.Open(mysql.Open(dsn), &gorm.Config{})
      ...
```

Env File:
```
SQL_CONNECTOR=user_production:password_production@tcp(mysql.server.com:3306)/production_dbname?charset=utf8mb4&parseTime=True&loc=Local
```
